package NaturalBiomes2.Lib;

public class BiomeIds {
	//Default Biome Ids
    public static int BIRCH_JUNGLE_DEFAULT = 28;
    public static int BIRCH_MOUNTAINS_DEFAULT = 29;
    public static int BIRCH_WOODS_DEFAULT = 30;
    public static int DUNES_DEFAULT = 31;
    public static int FOREST_DEFAULT = 32;
    public static int EXTREME_BIRCH_WOODS_DEFAULT = 33;
    public static int EXTREME_DESERT_HILLS_DEFAULT = 34;
    public static int EXTREME_DUNES_DEFAULT = 35;
    public static int EXTREME_FORESTED_HILLS_DEFAULT = 36;
    public static int EXTREME_GRASS_HILLS_DEFAULT = 37;
    public static int EXTREME_MEADOW_HILLS_DEFAULT = 38;
    public static int EXTREME_WOODS_DEFAULT = 39;
    public static int EXTREME_PINE_HILLS_DEFAULT = 40;
    public static int EXTREME_SNOW_HILLS_DEFAULT = 41;
    public static int EXTREME_SPARSE_WOODS_DEFAULT = 42;
    public static int LUSH_FOREST_DEFAULT = 43;
    public static int LUSH_MOUNTAINS_DEFAULT = 44;
    public static int LUSH_PLAINS_DEFAULT = 45;
    public static int LUSH_SWAMP_DEFAULT = 46;
    public static int MASSIVE_HILLS_DEFAULT = 47;
    public static int MARSH_DEFAULT = 48;
    public static int MEADOWS_DEFAULT = 49; 
    public static int PINE_FOREST_DEFAULT = 50;
    public static int OAK_MOUNTAINS_DEFAULT = 51;
    public static int OAK_WOODS_DEFAULT = 52;
    public static int RAIN_FOREST_DEFAULT = 53;
    public static int SAVANNAH_DEFAULT = 54;
    public static int SHRUBLANDS_DEFAULT = 55;
    public static int SNOWY_FOREST_DEFAULT = 56;
    public static int SNOWY_OAK_MOUNTAINS_DEFAULT = 57;
    public static int SNOWY_SHRUBLANDS_DEFAULT = 58;
    public static int SNOWY_WOODS_DEFAULT = 59;
    public static int SPARSE_OAK_MOUNTAINS_DEFAULT = 60;
    public static int SPARSE_WOODS_DEFAULT = 61;
    public static int THICK_OAK_MOUNTAINS_DEFAULT = 62;
    public static int THICK_SWAMP_DEFAULT = 63;
    public static int THICK_WOODS_DEFAULT = 64;

    //Current Biome Ids
    public static int BIRCH_JUNGLE;
    public static int BIRCH_MOUNTAINS;
    public static int BIRCH_WOODS;
    public static int DUNES;
    public static int FOREST;
    public static int EXTREME_BIRCH_WOODS;
    public static int EXTREME_DESERT_HILLS;
    public static int EXTREME_DUNES;
    public static int EXTREME_FORESTED_HILLS;
    public static int EXTREME_GRASS_HILLS;
    public static int EXTREME_MEADOW_HILLS;
    public static int EXTREME_WOODS;
    public static int EXTREME_PINE_HILLS;
    public static int EXTREME_SNOW_HILLS;
    public static int EXTREME_SPARSE_WOODS;
    public static int LUSH_FOREST;
    public static int LUSH_MOUNTAINS;
    public static int LUSH_PLAINS;
    public static int LUSH_SWAMP;
    public static int MASSIVE_HILLS;
    public static int MARSH;
    public static int MEADOWS; 
    public static int PINE_FOREST;
    public static int OAK_MOUNTAINS;
    public static int OAK_WOODS;
    public static int RAIN_FOREST;
    public static int SAVANNAH;
    public static int SHRUBLANDS;
    public static int SNOWY_FOREST;
    public static int SNOWY_OAK_MOUNTAINS;
    public static int SNOWY_SHRUBLANDS;
    public static int SNOWY_WOODS;
    public static int SPARSE_OAK_MOUNTAINS;
    public static int SPARSE_WOODS;
    public static int THICK_OAK_MOUNTAINS;
    public static int THICK_SWAMP;
    public static int THICK_WOODS;
}
